config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root "home#index"
  get 'legal' => 'home#legal', as: 'legal'
  resources :how_do, only: [:index]
  resources :blog, only: [:index, :show] do
    resources :comments, only: [:create] do
    end
    collection do
      get 'category/:category/' => 'blog#category', as: 'category'
      get 'do_pdf/:post/' => 'blog#do_pdf', as: 'do_pdf'
    end
  end

  devise_for :users,
             controllers: {registrations: 'users/registrations'},
             path: "auth",
             path_names:
                 {sign_in: 'login', sign_out: 'logout', password: 'secret',
                  confirmation: 'verification', unlock: 'unblock',
                  registration: 'register', sign_up: 'cmon_let_me_in'
                 }
  resources :products, only: [:index, :show] do
    collection do
      get 'category/:category/' => 'products#category', as: 'category'
      get 'search' => 'products#search', as: 'search'
    end
  end

  post "basket/set_product" => 'basket#set_product', as: 'set_product'
  delete 'reset_basket' => 'basket#reset_basket'
  delete 'delete_basket_product/:id(.:format)', as: "delete_basket_product",
         to: 'basket#delete_basket_product'

  resources :orders, only: [:show, :new, :create]
  post "orders/:id(.:format)" => 'orders#show'
  resources :contact, only: [:index, :create]

  ######################### ADMIN ZONE ###############
  namespace :admin do
    get 'home' => 'home#index'
    post 'check_to_direct_link' => 'home#check_to_direct_link', as: 'check_to_direct_link'

    resources :users, except: [:show, :new, :create] do
      collection do
        get 'search' => 'users#search', as: 'search'
        get 'sort/:by' => 'users#sort', as: 'sort'
      end
    end

    #un producto puede contener imagenes de ProductPicture. Ademas se puede
    #buscar un producto desde el controlador producto en admin/product/search
    resources :products, except: [:show] do
      resources :product_pictures, only: [:create, :destroy]
      collection do
        get 'search' => 'products#search', as: 'search'
        get 'sort/:by' => 'products#sort', as: 'sort'
        get 'category/:category/' => 'products#category', as: 'category'
      end
    end

    resources :categories, except: [:show, :new, :edit]
    resources :post_categories, except: [:show, :new, :edit]

    resources :orders, only: [:index, :destroy, :update] do
      collection do
        get 'search' => 'orders#search', as: 'search'
        get 'sort/:by' => 'orders#sort', as: 'sort'
      end
    end

    resources :delivery_prices, except: [:show]

    resources :posts do
      collection do
        get 'search' => 'posts#search', as: 'search'
        get 'sort/:by' => 'posts#sort', as: 'sort'
        get 'category/:category/' => 'posts#category', as: 'category'
      end
    end

    resources :comments, except: [:show, :new, :create] do
      collection do
        get 'search' => 'comments#search', as: 'search'
      end
    end
  end
end

app/views/order_notifier/admin_notify_order.html.erb
<h1 style="color: #5e9ca0;">Pedido realizado con &eacute;xito. Ref: <%=@order.id%></h1>
<br/><br/>
<p align="center">
  <%=Rails.env.production?? image_tag("http://tejeycome.es/assets/logo.png"):image_tag("http://localhost:3000/assets/logo.png")%>
</p>
<h1>Usuario con nombre [<%=@order.user.name%>] y teléfono [<%=@order.user.phone%>]</h1>
<h2>Forma de pago : <%=@order.pay_method.to_s.upcase%></h2>
<p>&nbsp;</p>
<h2 style="color: #2e6c80;">DATOS DEL CLIENTE:</h2>
<ul style="list-style-type: square;">
  <li>Nombre: <%=@order.user.name%></li>
  <li>Apellidos: <%=@order.user.surname1%> <%=@order.user.surname2%></li>
  <li>Direccion de envio: <%=@order.user.address%></li>
  <li>Tel&eacute;fono: <%=@order.user.phone%></li>
  <li>Email: <%=@order.user.email%></li>
</ul>
<h2 style="color: #2e6c80;">DATOS DEL PEDIDO:</h2>
<ul style="list-style-type: square;">
  <li>Ref: <%=@order.id%></li>
  <li>Direcci&oacute;n de envio: <%=@order.address%></li>
  <li>M&eacute;todo de pago: <%=@order.pay_method%></li>
  <li>Estado del pedido: <%=@order.state%></li>
  <li>Comentario al pedido: <%=@order.comment.html_safe%></li>
</ul>
<h2 style="color: #2e6c80;">PRODUCTOS DEL PEDIDO:</h2>
<table style="background-color: #FFF8C9;border-spacing: 10px;border: 1px solid black" align="center">
  <thead>
  <tr>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 50px;">REF.</td>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 100px;">Nombre</td>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 50px;">Cantidad</td>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 50px;">Precio</td>
  </tr>
  </thead>
  <tbody>
  <tr>
    <%@order.solds.sort.each do |cart|%>
        <%@product=cart.product%>
        <td style="text-align: center;"><strong style="font-size: 17px; color: #2b2301;"> <%=@product.id%></strong></td>
        <td style="text-align: center;"><strong style="font-size: 17px; color: #2b2301;"><%=link_to @product.name, product_url(@product)  %></strong></td>
        <td style="text-align: center;"><strong style="font-size: 17px; color: #2b2301;"><%=cart.quantity%></strong></td>
        <td><strong style="font-size: 17px; color: #2b2301;"><span style="float: right !important;"><%=number_with_precision(cart.price, precision: 2).to_s+' €'%></span></strong></td>
        </tr>
    <%end%>
    <tr><td>&nbsp;</td><td>&nbsp;</td>&nbsp;<td>&nbsp;</td><td>&nbsp;</td></tr>
    <tr>
      <td></td>
      <td></td>
      <td><span style="float: right !important;"><%= t('basket.stored_delivery_total') %></span></td>
      <td><span style="float: right !important;"><%=number_with_precision(@order.delivery_price, precision: 2).to_s+' €'%></span></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td><strong style="font-size: 17px; color: #2b2301;"><span style="float: right !important;"><%= t('basket.stored_products_total') %></span></strong></td>
      <td><strong style="font-size: 17px; color: #2b2301;"><span style="float: right !important;"><%=number_with_precision(@order.price, precision: 2).to_s+' €'%></span></strong></td>
    </tr>
    </tbody>
</table>
<p><strong>&nbsp;</strong></p>
<p><strong><%=link_to 'TejeyCome.es', 'http://tejeycome.es'%> donde encontraras dulces, cocina, bordados y mucho ganchillo.</strong></p>
<p><strong>Telf: 627 98 08 77 </strong></p>
<p><strong>Email: tejeycome@gmail.com </strong></p>
<p>&nbsp;</p>
<p><strong>&nbsp;</strong></p>

app/views/order_notifier/bank_transfer.html.erb
<h1 style="color: #5e9ca0;">Pedido realizado con &eacute;xito. Ref: <%=@order.id%></h1>
<br/><br/>
<p align="center">
  <%=Rails.env.production?? image_tag("http://tejeycome.es/assets/logo.png"):image_tag("http://localhost:3000/assets/logo.png")%>
</p>
<h1><%=@order.user.name%></h1>
<p>Gracias por su pedido en TejeyCome.es. Una vez que su paquete este listo le enviaremos un correoelectr&oacute;nico con instrucciones para el seguimiento de su pedido. Usted puede comprobar el estado de su pedido en <%= link_to "Accediendo en su cuenta".html_safe, admin_home_url %>.Si usted tiene alguna pregunta acerca de su pedido, por favor contacte con nosotros en tejeycome@gmail.com o desde cualqueir contacto en <%= link_to contact_index_url, contact_index_url %>.La confirmaci&oacute;n de su orden est&aacute; debajo, Gracias.</p>
<h2 style="color: #2e6c80;">Forma de pago (Transferencia bancaria):</h2>
<p>Usted eligio como forma de pago, transferencia bancaria.</p>
<p>Para completar el proceso de pedido es necesar&iacute;o que realice la transferncia, nosotros comprobaremos el pago con la m&aacute;xima brevedad y nos pondremos manos a la obra para completar su pedido. Es importante que nos indique el n&uacute;mero de Ref. del pedido como descripcion de la transferencia. Aqu&iacute; le dejamos un resumen:</p>
<p>&nbsp;</p>
<ul style="list-style-type: square;">
  <li><strong>Descripción de la transferencia: <br /></strong>
    <p style="text-align: center;"><strong><span style="background-color: #2b2301; color: #fff; display: inline-block; padding: 3px 10px; font-weight: bold; border-radius: 5px;">TejeyCome.es pedido con Ref: <%=@order.id%><br /></span></strong></p>
  </li>
  <li><strong><strong>N&uacute;mero de banco: <br /></strong></strong>
    <p style="text-align: center;"><strong><span style="background-color: #2b2301; color: #fff; display: inline-block; padding: 3px 10px; font-weight: bold; border-radius: 5px;"><%=ENV['TEJEYCOME_ACOUNT_BANK']%></span></strong></p>
  </li>
</ul>
<p>&nbsp;</p>
<h2 style="color: #2e6c80;">DATOS DEL CLIENTE:</h2>
<ul style="list-style-type: square;">
  <li>Nombre: <%=@order.user.name%></li>
  <li>Apellidos: <%=@order.user.surname1%> <%=@order.user.surname2%></li>
  <li>Dirección de envio: <%=@order.user.address%></li>
  <li>Tel&eacute;fono: <%=@order.user.phone%></li>
  <li>Email: <%=@order.user.email%></li>
</ul>
<h2 style="color: #2e6c80;">DATOS DEL PEDIDO:</h2>
<ul style="list-style-type: square;">
  <li>Ref: <%=@order.id%></li>
  <li>Direcci&oacute;n de envio: <%=@order.address%></li>
  <li>M&eacute;todo de pago: <%=@order.pay_method%></li>
  <li>Estado del pedido: <%=@order.state%></li>
  <li>Comentario al pedido: <%=@order.comment.html_safe%></li>
</ul>
<h2 style="color: #2e6c80;">PRODUCTOS DEL PEDIDO:</h2>
<table style="background-color: #FFF8C9;border-spacing: 10px;border: 1px solid black" align="center">
  <thead>
  <tr>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 50px;">REF.</td>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 100px;">Nombre</td>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 50px;">Cantidad</td>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 50px;">Precio</td>
  </tr>
  </thead>
  <tbody>
  <tr>
    <%@order.solds.sort.each do |cart|%>
        <%@product=cart.product%>
        <td style="text-align: center;"><strong style="font-size: 17px; color: #2b2301;"> <%=@product.id%></strong></td>
        <td style="text-align: center;"><strong style="font-size: 17px; color: #2b2301;"><%=link_to @product.name, product_url(@product)  %></strong></td>
        <td style="text-align: center;"><strong style="font-size: 17px; color: #2b2301;"><%=cart.quantity%></strong></td>
        <td><strong style="font-size: 17px; color: #2b2301;"><span style="float: right !important;"><%=number_with_precision(cart.price, precision: 2).to_s+' €'%></span></strong></td>
        </tr>
    <%end%>
    <tr><td>&nbsp;</td><td>&nbsp;</td>&nbsp;<td>&nbsp;</td><td>&nbsp;</td></tr>
    <tr>
      <td></td>
      <td></td>
      <td><span style="float: right !important;"><%= t('basket.stored_delivery_total') %></span></td>
      <td><span style="float: right !important;"><%=number_with_precision(@order.delivery_price, precision: 2).to_s+' €'%></span></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td><strong style="font-size: 17px; color: #2b2301;"><span style="float: right !important;"><%= t('basket.stored_products_total') %></span></strong></td>
      <td><strong style="font-size: 17px; color: #2b2301;"><span style="float: right !important;"><%=number_with_precision(@order.price, precision: 2).to_s+' €'%></span></strong></td>
    </tr>
    </tbody>
</table>
<p><strong>&nbsp;</strong></p>
<p><strong><%=link_to 'TejeyCome.es', 'http://tejeycome.es'%> donde encontraras dulces, cocina, bordados y mucho ganchillo.</strong></p>
<p><strong>Telf: 627 98 08 77 </strong></p>
<p><strong>Email: tejeycome@gmail.com </strong></p>
<p>&nbsp;</p>
<p><strong>&nbsp;</strong></p>

app/views/order_notifier/change_order.html.erb
<h1 style="color: #5e9ca0;">Su pedido con Ref: <%=@order.id%> ha cambiado de estado</h1>
<br/><br/>
<p align="center">
  <%=Rails.env.production?? image_tag("http://tejeycome.es/assets/logo.png"):image_tag("http://localhost:3000/assets/logo.png")%>
</p>
<h1><%=@order.user.name%></h1>
<p>&nbsp;</p>
<h2 style="color: #2e6c80;">DATOS DEL CLIENTE:</h2>
<ul style="list-style-type: square;">
  <li>Nombre: <%=@order.user.name%></li>
  <li>Apellidos: <%=@order.user.surname1%> <%=@order.user.surname2%></li>
  <li>Dirección de envio: <%=@order.user.address%></li>
  <li>Tel&eacute;fono: <%=@order.user.phone%></li>
  <li>Email: <%=@order.user.email%></li>
</ul>
<h2 style="color: #2e6c80;">DATOS DEL PEDIDO:</h2>
<ul style="list-style-type: square;">
  <li>Ref: <%=@order.id%></li>
  <li>Direcci&oacute;n de envio: <%=@order.address%></li>
  <li>M&eacute;todo de pago: <%=@order.pay_method%></li>
  <li>Estado del pedido: <b><%=@order.state%></b></li>
  <li>Código de seguimiento (<%=link_to 'www.correos.es', 'http://www.correos.es/ss/Satellite/site/aplicacion-1349167812834-herramientas_y_apps/detalle_app-sidioma=es_ES'  %>): <b><%=@order.cod_delivery%></b></li>
  <li>Comentario al pedido: <%=@order.comment.html_safe%></li>
</ul>
<h2 style="color: #2e6c80;">PRODUCTOS DEL PEDIDO:</h2>
<table style="background-color: #FFF8C9;border-spacing: 10px;border: 1px solid black" align="center">
  <thead>
  <tr>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 50px;">REF.</td>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 100px;">Nombre</td>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 50px;">Cantidad</td>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 50px;">Precio</td>
  </tr>
  </thead>
  <tbody>
  <tr>
    <%@order.solds.sort.each do |cart|%>
        <%@product=cart.product%>
        <td style="text-align: center;"><strong style="font-size: 17px; color: #2b2301;"> <%=@product.id%></strong></td>
        <td style="text-align: center;"><strong style="font-size: 17px; color: #2b2301;"><%=link_to @product.name, product_url(@product)  %></strong></td>
        <td style="text-align: center;"><strong style="font-size: 17px; color: #2b2301;"><%=cart.quantity%></strong></td>
        <td><strong style="font-size: 17px; color: #2b2301;"><span style="float: right !important;"><%=number_with_precision(cart.price, precision: 2).to_s+' €'%></span></strong></td>
        </tr>
    <%end%>
    <tr><td>&nbsp;</td><td>&nbsp;</td>&nbsp;<td>&nbsp;</td><td>&nbsp;</td></tr>
    <tr>
      <td></td>
      <td></td>
      <td><span style="float: right !important;"><%= t('basket.stored_delivery_total') %></span></td>
      <td><span style="float: right !important;"><%=number_with_precision(@order.delivery_price, precision: 2).to_s+' €'%></span></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td><strong style="font-size: 17px; color: #2b2301;"><span style="float: right !important;"><%= t('basket.stored_products_total') %></span></strong></td>
      <td><strong style="font-size: 17px; color: #2b2301;"><span style="float: right !important;"><%=number_with_precision(@order.price, precision: 2).to_s+' €'%></span></strong></td>
    </tr>
    </tbody>
</table>
<p><strong>&nbsp;</strong></p>
<p><strong><%=link_to 'TejeyCome.es', 'http://tejeycome.es'%> donde encontraras dulces, cocina, bordados y mucho ganchillo.</strong></p>
<p><strong>Telf: 627 98 08 77 </strong></p>
<p><strong>Email: tejeycome@gmail.com </strong></p>
<p>&nbsp;</p>
<p><strong>&nbsp;</strong></p>

app/views/order_notifier/credit_card.html.erb
<h1 style="color: #5e9ca0;">Pedido realizado con &eacute;xito. Ref: <%=@order.id%></h1>
<br/><br/>
<p align="center">
  <%=Rails.env.production?? image_tag("http://tejeycome.es/assets/logo.png"):image_tag("http://localhost:3000/assets/logo.png")%>
</p>
<h1><%=@order.user.name%></h1>
<p>Gracias por su pedido en TejeyCome.es. Una vez que su paquete este listo le enviaremos un correoelectr&oacute;nico con instrucciones para el seguimiento de su pedido. Usted puede comprobar el estado de su pedido en <%= link_to "Accediendo en su cuenta".html_safe, admin_home_url %>.Si usted tiene alguna pregunta acerca de su pedido, por favor contacte con nosotros en tejeycome@gmail.com o desde cualqueir contacto en <%= link_to contact_index_url, contact_index_url %>.La confirmaci&oacute;n de su orden est&aacute; debajo, Gracias.</p>
<p>Usted eligio como forma de pago, Tarjeta de Credito.</p>
<p>&nbsp;</p>
<h2 style="color: #2e6c80;">DATOS DEL CLIENTE:</h2>
<ul style="list-style-type: square;">
  <li>Nombre: <%=@order.user.name%></li>
  <li>Apellidos: <%=@order.user.surname1%> <%=@order.user.surname2%></li>
  <li>Direccion de envio: <%=@order.user.address%></li>
  <li>Tel&eacute;fono: <%=@order.user.phone%></li>
  <li>Email: <%=@order.user.email%></li>
</ul>
<h2 style="color: #2e6c80;">DATOS DEL PEDIDO:</h2>
<ul style="list-style-type: square;">
  <li>Ref: <%=@order.id%></li>
  <li>Direcci&oacute;n de envio: <%=@order.address%></li>
  <li>M&eacute;todo de pago: <%=@order.pay_method%></li>
  <li>Estado del pedido: <%=@order.state%></li>
  <li>Comentario al pedido: <%=@order.comment.html_safe%></li>
</ul>
<h2 style="color: #2e6c80;">PRODUCTOS DEL PEDIDO:</h2>
<table style="background-color: #FFF8C9;border-spacing: 10px;border: 1px solid black" align="center">
  <thead>
  <tr>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 50px;">REF.</td>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 100px;">Nombre</td>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 50px;">Cantidad</td>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 50px;">Precio</td>
  </tr>
  </thead>
  <tbody>
  <tr>
    <%@order.solds.sort.each do |cart|%>
        <%@product=cart.product%>
        <td style="text-align: center;"><strong style="font-size: 17px; color: #2b2301;"> <%=@product.id%></strong></td>
        <td style="text-align: center;"><strong style="font-size: 17px; color: #2b2301;"><%=link_to @product.name, product_url(@product)  %></strong></td>
        <td style="text-align: center;"><strong style="font-size: 17px; color: #2b2301;"><%=cart.quantity%></strong></td>
        <td><strong style="font-size: 17px; color: #2b2301;"><span style="float: right !important;"><%=number_with_precision(cart.price, precision: 2).to_s+' €'%></span></strong></td>
        </tr>
    <%end%>
    <tr><td>&nbsp;</td><td>&nbsp;</td>&nbsp;<td>&nbsp;</td><td>&nbsp;</td></tr>
    <tr>
      <td></td>
      <td></td>
      <td><span style="float: right !important;"><%= t('basket.stored_delivery_total') %></span></td>
      <td><span style="float: right !important;"><%=number_with_precision(@order.delivery_price, precision: 2).to_s+' €'%></span></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td><strong style="font-size: 17px; color: #2b2301;"><span style="float: right !important;"><%= t('basket.stored_products_total') %></span></strong></td>
      <td><strong style="font-size: 17px; color: #2b2301;"><span style="float: right !important;"><%=number_with_precision(@order.price, precision: 2).to_s+' €'%></span></strong></td>
    </tr>
    </tbody>
</table>
<p><strong>&nbsp;</strong></p>
<p><strong><%=link_to 'TejeyCome.es', 'http://tejeycome.es'%> donde encontraras dulces, cocina, bordados y mucho ganchillo.</strong></p>
<p><strong>Telf: 627 98 08 77 </strong></p>
<p><strong>Email: tejeycome@gmail.com </strong></p>
<p>&nbsp;</p>
<p><strong>&nbsp;</strong></p>

app/views/order_notifier/paypal.html.erb
<h1 style="color: #5e9ca0;">Pedido realizado con &eacute;xito. Ref: <%=@order.id%></h1>
<br/><br/>
<p align="center">
  <%=Rails.env.production?? image_tag("http://tejeycome.es/assets/logo.png"):image_tag("http://localhost:3000/assets/logo.png")%>
</p>
<h1><%=@order.user.name%></h1>
<p>Gracias por su pedido en TejeyCome.es. Una vez que su paquete este listo le enviaremos un correoelectr&oacute;nico con instrucciones para el seguimiento de su pedido. Usted puede comprobar el estado de su pedido en <%= link_to "Accediendo en su cuenta".html_safe, admin_home_url %>.Si usted tiene alguna pregunta acerca de su pedido, por favor contacte con nosotros en tejeycome@gmail.com o desde cualqueir contacto en <%= link_to contact_index_url, contact_index_url %>.La confirmaci&oacute;n de su orden est&aacute; debajo, Gracias.</p>
<p>Usted eligio como forma de pago, PayPal.</p>
<p>&nbsp;</p>
<h2 style="color: #2e6c80;">DATOS DEL CLIENTE:</h2>
<ul style="list-style-type: square;">
  <li>Nombre: <%=@order.user.name%></li>
  <li>Apellidos: <%=@order.user.surname1%> <%=@order.user.surname2%></li>
  <li>Direccion de envio: <%=@order.user.address%></li>
  <li>Tel&eacute;fono: <%=@order.user.phone%></li>
  <li>Email: <%=@order.user.email%></li>
</ul>
<h2 style="color: #2e6c80;">DATOS DEL PEDIDO:</h2>
<ul style="list-style-type: square;">
  <li>Ref: <%=@order.id%></li>
  <li>Direcci&oacute;n de envio: <%=@order.address%></li>
  <li>M&eacute;todo de pago: <%=@order.pay_method%></li>
  <li>Estado del pedido: <%=@order.state%></li>
  <li>Comentario al pedido: <%=@order.comment.html_safe%></li>
</ul>
<h2 style="color: #2e6c80;">PRODUCTOS DEL PEDIDO:</h2>
<table style="background-color: #FFF8C9;border-spacing: 10px;border: 1px solid black" align="center">
  <thead>
  <tr>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 50px;">REF.</td>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 100px;">Nombre</td>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 50px;">Cantidad</td>
    <td style="background:#0073b7;color:white;border: 1px solid black;margin: 0px !important;padding: 10px 50px;">Precio</td>
  </tr>
  </thead>
  <tbody>
  <tr>
    <%@order.solds.sort.each do |cart|%>
        <%@product=cart.product%>
        <td style="text-align: center;"><strong style="font-size: 17px; color: #2b2301;"> <%=@product.id%></strong></td>
        <td style="text-align: center;"><strong style="font-size: 17px; color: #2b2301;"><%=link_to @product.name, product_url(@product)  %></strong></td>
        <td style="text-align: center;"><strong style="font-size: 17px; color: #2b2301;"><%=cart.quantity%></strong></td>
        <td><strong style="font-size: 17px; color: #2b2301;"><span style="float: right !important;"><%=number_with_precision(cart.price, precision: 2).to_s+' €'%></span></strong></td>
        </tr>
    <%end%>
    <tr><td>&nbsp;</td><td>&nbsp;</td>&nbsp;<td>&nbsp;</td><td>&nbsp;</td></tr>
    <tr>
      <td></td>
      <td></td>
      <td><span style="float: right !important;"><%= t('basket.stored_delivery_total') %></span></td>
      <td><span style="float: right !important;"><%=number_with_precision(@order.delivery_price, precision: 2).to_s+' €'%></span></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td><strong style="font-size: 17px; color: #2b2301;"><span style="float: right !important;"><%= t('basket.stored_products_total') %></span></strong></td>
      <td><strong style="font-size: 17px; color: #2b2301;"><span style="float: right !important;"><%=number_with_precision(@order.price, precision: 2).to_s+' €'%></span></strong></td>
    </tr>
    </tbody>
</table>
<p><strong>&nbsp;</strong></p>
<p><strong><%=link_to 'TejeyCome.es', 'http://tejeycome.es'%> donde encontraras dulces, cocina, bordados y mucho ganchillo.</strong></p>
<p><strong>Telf: 627 98 08 77 </strong></p>
<p><strong>Email: tejeycome@gmail.com </strong></p>
<p>&nbsp;</p>
<p><strong>&nbsp;</strong></p>