config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root "home#index"
  get 'legal' => 'home#legal', as: 'legal'
  resources :how_do, only: [:index]
  resources :blog, only: [:index, :show] do
    resources :comments, only: [:create] do
    end
    collection do
      get 'category/:category/' => 'blog#category', as: 'category'
      get 'do_pdf/:post/' => 'blog#do_pdf', as: 'do_pdf'
    end
  end

  devise_for :users,
             controllers: {registrations: 'users/registrations'},
             path: "auth",
             path_names:
                 {sign_in: 'login', sign_out: 'logout', password: 'secret',
                  confirmation: 'verification', unlock: 'unblock',
                  registration: 'register', sign_up: 'cmon_let_me_in'
                 }
  resources :products, only: [:index, :show] do
    collection do
      get 'category/:category/' => 'products#category', as: 'category'
      get 'search' => 'products#search', as: 'search'
    end
  end

  post "basket/set_product" => 'basket#set_product', as: 'set_product'
  delete 'reset_basket' => 'basket#reset_basket'
  delete 'delete_basket_product/:id(.:format)', as: "delete_basket_product",
         to: 'basket#delete_basket_product'

  resources :orders, only: [:show, :new, :create]
  post "orders/:id(.:format)" => 'orders#show'
  resources :contact, only: [:index, :create]

  ######################### ADMIN ZONE ###############
  namespace :admin do
    get 'home' => 'home#index'
    post 'check_to_direct_link' => 'home#check_to_direct_link', as: 'check_to_direct_link'

    resources :users, except: [:show, :new, :create] do
      collection do
        get 'search' => 'users#search', as: 'search'
        get 'sort/:by' => 'users#sort', as: 'sort'
      end
    end

    #un producto puede contener imagenes de ProductPicture. Ademas se puede
    #buscar un producto desde el controlador producto en admin/product/search
    resources :products, except: [:show] do
      resources :product_pictures, only: [:create, :destroy]
      collection do
        get 'search' => 'products#search', as: 'search'
        get 'sort/:by' => 'products#sort', as: 'sort'
        get 'category/:category/' => 'products#category', as: 'category'
      end
    end

    resources :categories, except: [:show, :new, :edit]
    resources :post_categories, except: [:show, :new, :edit]

    resources :orders, only: [:index, :destroy, :update] do
      collection do
        get 'search' => 'orders#search', as: 'search'
        get 'sort/:by' => 'orders#sort', as: 'sort'
      end
    end

    resources :delivery_prices, except: [:show]

    resources :posts do
      collection do
        get 'search' => 'posts#search', as: 'search'
        get 'sort/:by' => 'posts#sort', as: 'sort'
        get 'category/:category/' => 'posts#category', as: 'category'
      end
    end

    resources :comments, except: [:show, :new, :create] do
      collection do
        get 'search' => 'comments#search', as: 'search'
      end
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  include BasketHelper
  include PayPal::SDK::REST
  has_many :solds
  belongs_to :user

  PAGE_INDEX=10 #numero de entradas que se veran en la accion index (menu admin)

  # mostrar solo los pedidos del usuario actual en su menu de administracion
  scope :from_current_customer, -> (current_user) { where(user_id: current_user.id) }
  # mostrar los pedidos que aun no han sido enviados pero si pagados
  scope :pending_shipping, -> {where(state: I18n.t('order.state2')) }
  # mostrar los pedidos que aun no han sido pagados
  scope :outstanding_payment, -> { where(state: I18n.t('order.state1')) }
  # mostrar los pedidos realizados este mes
  scope :this_month, -> {where('created_at BETWEEN ? AND ?', Time.now.beginning_of_month,Time.now.end_of_month)}


  def new_cart

    unique_products_basket.each do |product|
      p=Product.find(product)
     Sold.create(product_id: p.id,order_id: @order.id,
                    quantity: count_num_products_in_basket(p),price: p.price)
    end
  end

  def paypal_url(url)
    # TODO repasar direcciones para produccion
    self.update_attribute(:token_paypal,SecureRandom.hex(35)) # preparo un token de vuelta para paypal
    values = {
        # Valores generales
        business: Rails.env.production??
            ENV['MAIL_USER_NAME']: ENV['PAY_PAL_VENDOR_EMAIL'], #el que recibe el pago
        cmd: '_cart',
        upload: 1,
        return: Rails.env.production??
            url.to_s+"orders/#{self.id.to_s}":'http://localhost:3000/'+"orders/#{self.id.to_s}", #pagina de respuesta, ej. /orders/1
        invoice: self.id.to_s,
        currency_code: 'EUR',
        cpp_logo_image: Rails.env.production??
            url.to_s+'assets/logoweb_paypal.png':'http://localhost:3000/assets/logoweb_paypal.png', #imagen para web checkout paypal 190x60
        lc: 'ES',
        rm: '2', # volvemos usando POST con todas las variables del pedido
        custom: self.token_paypal # este token nos sera devuelto para comprobar la autenticidad de la compra
    }
    # Valores del pedido
    values.merge!({
                      # The amount is in cents
                      "amount_1" => "%.2f" % self.price.to_s, #precio del pedido
                      "item_name_1" => "TejeyCome [Ref:#{self.id}]", #nombre del pedido
                      "item_number_1" => self.id.to_s, #referencia del pedido
                      "quantity_1" => 1 #la cantidad, que es uno siempre
                  })
    # para entorno de producccion: https://www.paypal.com/cgi-bin/webscr?
    # Informacion: https://www.paypal.com/es/cgi-bin/webscr?cmd=p/sell/ipn-test-outside

    Rails.env.production??
        "https://www.paypal.com/cgi-bin/webscr?" + values.to_query : "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end
  def check_credit_card(credit_card)
    Rails.logger.error "--------chequeando tarjeta: "+ credit_card.valid?.to_s
    credit_card.valid?
    # TODO comprobar esto porque no esta probado
    # Build Payment object
    @payment = Payment.new({
                               :intent => "sale",
                               :payer => {
                                   :payment_method => "credit_card",
                                   :funding_instruments => [{
                                                                :credit_card => {
                                                                    :type => Rails.env.production?? credit_card.type : "visa",
                                                                    :number => Rails.env.production?? credit_card.number : "4567516310777851",
                                                                    :expire_month => Rails.env.production?? credit_card.expire_month : "11",
                                                                    :expire_year => Rails.env.production?? credit_card.expire_year : "2018",
                                                                    :cvv2 => Rails.env.production?? credit_card.cvv2 : "847",
                                                                    :first_name => Rails.env.production?? credit_card.first_name : "Joe",
                                                                    :last_name => Rails.env.production?? credit_card.last_name : "Shopper",
                                                                    :billing_address => {
                                                                        :line1 => self.address,
                                                                        :city => "SANTA CRUZ DE MUDELA",
                                                                        :state => "Ciudad Real",
                                                                        :postal_code => "13730",
                                                                        :country_code => "ES" }}}]},
                               :transactions => [{
                                                     :item_list => {
                                                         :items => [{
                                                                        :name => "TejeyCome [Ref:#{self.id}]", #nombre del pedido,
                                                                        :sku =>"TejeyCome [Ref:#{self.id}]", #nombre del pedido,
                                                                        :price => "%.2f" % self.price,
                                                                        :currency => "EUR",
                                                                        :quantity => 1 }]},
                                                     :amount => {
                                                         :total => "%.2f" % self.price,
                                                         :currency => "EUR" },
                                                     :description =>  "TejeyCome [Ref:#{self.id}]"}]})

    # Create Payment and return the status(true or false)
    if @payment.create
      @payment.id     # Payment Id
      true
    else
      @payment.error  # Error Hash
      false
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_filter :authenticate_user! # es necesario estar autenticado para continuar
  load_and_authorize_resource # carga los permisos para el modelo por defecto de este controlador
  layout 'admin/admin'
  before_action :set_order, only: [:update, :destroy]

  def index
    if current_user.is_customer?
      @orders = Order.from_current_customer(current_user).paginate(page: params[:page], per_page: Order::PAGE_INDEX).order('created_at DESC')
      render :index_customer

    elsif current_user.is_admin?
      @orders = Order.paginate(page: params[:page], per_page: Order::PAGE_INDEX).order('created_at DESC')
    end

  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        # mando email al cliente si se pidio en el formulario
        OrderNotifier.change_order(@order, @web_title).deliver_now if params[:send_mail_customer]
        format.html { redirect_to :back, notice: t('admin_zone.orders.edit_notify', ref: @order.id) }
      else
        format.html { render :index,  t('admin_zone.orders.edit_alert',ref: @order.id)  }
      end
    end
  end

  def search
    param=params[:search][:text]
    # busqueda por email del cliente o por ref
    if current_user.is_customer?
      search= Order.where(user_id: User.where(email: param)).union(Order.where(id: param)).where(user_id: current_user.id)
      @orders = search.paginate(page: params[:page], per_page: Order::PAGE_INDEX)
      render "index_customer"
     elsif current_user.is_admin?
      search= Order.where(user_id: User.where(email: param)).union(Order.where(id: param))
      @orders = search.paginate(page: params[:page], per_page: Order::PAGE_INDEX)
      render "index"
    end
  end

  def sort
    case params[:by]
      when 'outstanding_payment'
        @subtitle=t('admin_zone.home.outstanding_payment')
        @orders=Order.outstanding_payment.paginate(page: params[:page], per_page: Order::PAGE_INDEX).order('created_at DESC')
      when 'pending_shipping'
        @subtitle=t('admin_zone.home.pending_shipping')
        @orders=Order.pending_shipping.paginate(page: params[:page], per_page: Order::PAGE_INDEX).order('created_at DESC')
      when 'orders_this_month'
        @subtitle=t('admin_zone.home.orders_this_month')
        @orders=Order.this_month.paginate(page: params[:page], per_page: Order::PAGE_INDEX).order('created_at DESC')
      else
        @orders = Order.paginate(page: params[:page], per_page: Order::PAGE_INDEX).order('created_at DESC')
    end
    render "index"
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to  admin_products_path , notice: t('admin_zone.orders.destroy_notify') }
    end
  end

  private
  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:address, :pay_method,:comment,:state, :cod_delivery, :price)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include BasketHelper
  protect_from_forgery except: :show #hace que al volver de paypal no se rompa la sesion de Devise
  respond_to :html

  def show # en esta accion no se vigila el token de autenticacion por la vuelta con PayPal, es importante vigilar de cerca la seguridad
    @web_title="TejeyCome.es - Pedido [#{params[:id]}]"
    @order = Order.find(params[:id])
    #vigilo que el usuario que viene de un pedido de PayPal sea el que lo creo o administrador
    if @order.user == current_user  || @order.user.is_admin?
      if (params[:payment_status] == 'Pending' || params[:payment_status] == 'Completed') && params[:custom] == @order.token_paypal
      # observo si se pago correctamente por PayPal y la seguridad
        # Pending= pendiente de aceptar el pago por el vendedor (pago correcto), Completed= pago completamente realizado
        @order.update_attribute(:state, t('order.state2'))
        @order.update_attribute(:token_paypal, nil) # libero espacio de la base de datos inutil
        # Mando un mail al cliente avisandole de su pedido por PayPal
        OrderNotifier.paypal(@order, @web_title).deliver_now
        # Mando email al administrador para que sepa de un pedido nuevo
        OrderNotifier.admin_notify_order(@order, @web_title).deliver_now
        flash[:notice] = t('order.new', ref: @order.id)
      else # por si existe algun problema  con el pago por PayPal
        flash[:alert] = t('order.new_alert', ref: @order.id) if @order.state == t('order.state1')
      end
      flash[:notice] = t('order.new', ref: @order.id)
      respond_with(@order)
    else # si no eres el usuario que hizo el pedido, redireccion a root_path
      redirect_to root_path, alert: t('common.no_permited')
    end
  end

  def new
    @web_title='TejeyCome.es - Nuevo Pedido'
    if user_signed_in?
      if total_products > 0
        @load_javascript += 'run_wysihtml5();'
        @credit_card = CreditCard.new
        @show_credit_card_form=false
        @order = Order.new(user_id: current_user.id,
                           address: current_user.address)
        respond_with(@order, @show_credit_card_form, @credit_card)
      else
        redirect_to :back, alert: t('product.nothing')
      end
    else
      redirect_to new_user_registration_path, alert: t('order.need_register')
    end
  end

  def create
    # doy permisos y agrego parametros al pedido
    @order = Order.new(order_params)
    # agrego ususario
    @order.user_id=current_user.id
    #pongo los gastos de envio
    @order.delivery_price=view_context.delivery_cart_price
    # agrego precio total del pedido
    @order.price=total_products+@order.delivery_price
    #guardo el pedido
    @order.save
    # creo un carrito para este pedido lleno de productos
    unique_products_basket.each do |product|
      p=Product.find(product)
      Sold.create(product_id: p.id, order_id: @order.id,
                  quantity: count_num_products_in_basket(p), price: p.price)
    end
    # vacio el carrito de la sesion
    temp_basket=session[:basket] # guardo el carrito por si la tarjeta de credito falla
    session[:basket]=Array.new
    ##################################################

    # decido donde ir segun metodo de pago
    case @order.pay_method
      when t('order.pay_method1') #----------------------------------------- transferencia
        flash[:notice] = t('order.new', ref: @order.id)
        # Mando email al cliente con informacion para realizar el pago por transferencia
        OrderNotifier.bank_transfer(@order, @web_title).deliver_now
        # Mando email al administrador para que sepa de un pedido nuevo
        OrderNotifier.admin_notify_order(@order, @web_title).deliver_now
        respond_with(@order, location: order_path(@order))
      when t('order.pay_method2') #---------------------------------------------- paypal
        redirect_to @order.paypal_url(@url) #el parametro de la funcion es el dominio la web y el token de seguridad de rails
      when t('order.pay_method3') #--------------------------------------- tarjeta de credito
        @credit_card=CreditCard.new(params[:order][:credit_card])
        if @order.check_credit_card(@credit_card) && @credit_card.valid? # compruebo que el pago sea correcto
          @order.update_attribute(:state, t('order.state2'))
          # Mando email al cliente con informacion para realizar el pago por transferencia
          OrderNotifier.credit_card(@order, @web_title).deliver_now
          # Mando email al administrador para que sepa de un pedido nuevo
          OrderNotifier.admin_notify_order(@order, @web_title).deliver_now
          respond_with(@order, location: order_path(@order))
        else # fallo el pago por tarjeta
          flash[:alert]= t('order.alert_credit_card')
          @order.destroy # elimino el pedido
          session[:basket]=temp_basket # restauro cesta
          render :new, object: @credit_card
        end
      else
        render :new
    end
  end

  private
  def order_params
    params.require(:order).permit(:address, :pay_method, :comment)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def payment_options
    [[t('order.pay_method1')],[t('order.pay_method2')]]
  end
  def order_state
    [[t('order.state1')],[t('order.state2')],[t('order.state3')]]
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def credit_card_types
    [["visa"],["mastercard"],["discover"],["amex"]]
  end
end

app/views/admin/orders/index.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <%= t('admin_zone.orders.name') %>
    <small><%= t('admin_zone.navbar.orders.list') %></small>
  </h1>
  <br/>

  <div class="row">
    <div class="col-md-12">
      <div class="pull-right">
        <%= form_for(:search, url: search_admin_orders_path, method: 'get', html: {class: 'form-inline'}) do |f| %>
            <div class="form-group">
              <%= f.text_field :text, placeholder: t('admin_zone.products.search'), class: 'form-control' %>
            </div>
            <%= f.submit t('common.search'), class: 'btn btn-info' %>
        <% end %>
      </div>
      <div class="pull-left">
        <%= link_to t('admin_zone.home.outstanding_payment')+" (#{Order.outstanding_payment.count})", sort_admin_orders_path('outstanding_payment'), class: 'btn btn-warning' %>
        <%= link_to t('admin_zone.home.pending_shipping')+" (#{Order.pending_shipping.count})", sort_admin_orders_path('pending_shipping'), class: 'btn btn-warning' %>
        <%= link_to t('admin_zone.home.orders_this_month')+" (#{Order.this_month.count})", sort_admin_orders_path('orders_this_month'), class: 'btn btn-warning' %>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <i class="fa fa-shopping-cart"></i> <%= t('admin_zone.orders.list') %> <%= " (#{@subtitle})" unless @subtitle.blank? %>
          <div class="pull-right">
            <div class="btn-group">
            </div>
          </div>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
          <div class="row">
            <div class="col-lg-12">
              <% if @orders.blank? %>
                  <span class="col-xs-12 text-center"><%= t('admin_zone.orders.orders_blank').upcase %></span>
              <% else %>
                  <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped">
                      <thead>
                      <tr>
                        <th><%= t('admin_zone.orders.details') %></th>
                        <th><%= t('admin_zone.global.actions') %> </th>
                      </tr>
                      </thead>
                      <tbody>
                      <% @orders.each do |order| %>
                          <tr class="odd" role="row">
                            <td>
                              <div class="nav-tabs-custom">
                                <ul class="nav nav-tabs">
                                  <li class="active">
                                    <a href="#tab_<%= order.id %>_1" data-toggle="tab"><b><%= t('admin_zone.orders.resume') %></b></a>
                                  </li>
                                  <li>
                                    <a href="#tab_<%= order.id %>_2" data-toggle="tab"><b><%= t('admin_zone.orders.user') %></b></a>
                                  </li>
                                  <li>
                                    <a href="#tab_<%= order.id %>_3" data-toggle="tab"><b><%= t('admin_zone.orders.products') %></b></a>
                                  </li>
                                  <li>
                                    <a href="#tab_<%= order.id %>_4" data-toggle="tab"><b><%= t('admin_zone.orders.order_details') %></b></a>
                                  </li>

                                </ul>
                                <div class="tab-content">
                                  <div class="tab-pane active" id="tab_<%= order.id %>_1">
                                    <table class="table table-bordered">
                                      <tbody>
                                      <tr>
                                        <th>
                                          <%= t('helpers.label.order.price') %>
                                        </th>
                                        <th>
                                          <%= t('helpers.label.sold.quantity') %>
                                        </th>
                                        <th>
                                          <%= t('helpers.label.order.state') %>
                                        </th>
                                        <th>
                                          <%= t('helpers.label.order.created_at') %>
                                        </th>
                                      </tr>
                                      <tr>
                                        <td>
                                          <%= order.price %>
                                        </td>
                                        <td>
                                          <%= order.solds.sum(:quantity) %>
                                        </td>
                                        <td>
                                          <%= order.state %>
                                        </td>
                                        <td>
                                          <%= l order.created_at, format: :long3 %>
                                        </td>
                                      </tr>
                                      </tbody>
                                    </table>
                                  </div>
                                  <!-- /.tab-pane -->
                                  <div class="tab-pane" id="tab_<%= order.id %>_2">
                                    <table class="table table-bordered">
                                      <tbody>
                                      <tr>
                                        <th>
                                          <%= t('helpers.label.user.name') %>
                                        </th>
                                        <th>
                                          <%= t('helpers.label.user.phone') %>
                                        </th>
                                        <th>
                                          <%= t('helpers.label.user.email') %>
                                        </th>
                                      </tr>
                                      <tr>
                                        <td>
                                          <%= order.user.name %>
                                        </td>
                                        <td>
                                          <%= order.user.phone %>
                                        </td>
                                        <td>
                                          <%= order.user.email %>
                                        </td>
                                      </tr>
                                      </tbody>
                                    </table>
                                    <table class="table table-bordered">
                                      <tbody>
                                      <tr>
                                        <th>
                                          <%= t('helpers.label.user.surname1') %>
                                        </th>
                                        <th>
                                          <%= t('helpers.label.user.surname2') %>
                                        </th>
                                        <th>
                                          <%= t('helpers.label.user.address') %>
                                        </th>
                                      </tr>
                                      <tr>
                                        <td>
                                          <%= order.user.surname1 %>
                                        </td>
                                        <td>
                                          <%= order.user.surname2 %>
                                        </td>
                                        <td>
                                          <%= order.user.address %>
                                        </td>
                                      </tr>
                                      </tbody>
                                    </table>
                                  </div>
                                  <!-- /.tab-pane -->
                                  <div class="tab-pane" id="tab_<%= order.id %>_3">
                                    <% order.solds.in_groups_of(3).each do |group| %>
                                        <div class="row">
                                          <% group.each do |sold| %>
                                              <div class="col-lg-4 col-md-4 col-xs-12 thumb">
                                                <% if sold %>
                                                    <a class="btn btn-info btn-xs" role="button" data-toggle="collapse" href="#collapse-<%= sold.product.slug %>-<%= order.id %>" aria-expanded="false" aria-controls="collapseExample">
                                                      <i class="fa fa-eye"></i> <%= t('common.details') %>
                                                    </a>

                                                    <div class="collapse" id="collapse-<%= sold.product.slug %>-<%= order.id %>">
                                                      <div class="well">
                                                        <%= sold.product.name.upcase %><br/>
                                                        (<%= sold.product.category.name %>)<br/><br/>
                                                        <%= t('helpers.label.sold.price') %>: <%= sold.price %>€<br/>
                                                        <%= t('helpers.label.sold.quantity') %>: <%= sold.quantity %>
                                                        <br/>
                                                        <%= t('helpers.label.sold.total') %>
                                                        : <%= sold.price*sold.quantity %>€<br/>
                                                      </div>
                                                    </div>
                                                    <a class="thumbnail" href="#">
                                                      <%= image_tag sold.product.media, class: "img-responsive" %>
                                                    </a>
                                                    <%= link_to sold.product.name, product_path(sold.product) %>
                                                <% end %>
                                              </div>
                                          <% end %>
                                        </div>
                                    <% end %>
                                  </div>
                                  <!-- /.tab-pane -->
                                  <div class="tab-pane" id="tab_<%= order.id %>_4">
                                    <%= render 'admin/orders/form', order: order %>
                                  </div>
                                  <!-- /.tab-pane -->
                                  <span class="badge"><strong><%= t('helpers.label.order.id') %></strong> <%= order.id %></span>
                                </div>
                                <!-- /.tab-content -->
                              </div>
                            </td>
                            <td class="text-right">
                              <a class="btn btn-danger btn-xs" data-method="delete" href="<%= admin_order_path(order) %>">
                                <i class="fa fa-trash"></i> <%= t('common.delete') %>
                              </a>
                            </td>
                          </tr>
                      <% end %>
                      </tbody>
                    </table>
                  </div>
              <% end %>
              <!-- /.table-responsive -->
            </div>
            <!-- /.col-lg-4 (nested) -->
            <div class="col-lg-12">
              <div class="row">
                <div class="col-sm-5">
                </div>
                <div class="col-sm-12">
                  <%= will_paginate @collection, renderer: BootstrapPagination::Rails, previous_label: fa_icon("arrow-left"), next_label: fa_icon("arrow-right"),
                                    page_gap: t('will_paginate.page_gap'), class: 'pull-right' %>
                </div>
              </div>
            </div>
            <!-- /.col-lg-8 (nested) -->
          </div>
          <!-- /.row -->
        </div>
        <!-- /.panel-body -->
      </div>
      <!-- /.panel -->
    </div>
    <!-- /.col-lg-8 -->
  </div>
  <!-- /.row -->
</section>