config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root "home#index"
  get 'legal' => 'home#legal', as: 'legal'
  resources :how_do, only: [:index]
  resources :blog, only: [:index, :show] do
    resources :comments, only: [:create] do
    end
    collection do
      get 'category/:category/' => 'blog#category', as: 'category'
      get 'do_pdf/:post/' => 'blog#do_pdf', as: 'do_pdf'
    end
  end

  devise_for :users,
             controllers: {registrations: 'users/registrations'},
             path: "auth",
             path_names:
                 {sign_in: 'login', sign_out: 'logout', password: 'secret',
                  confirmation: 'verification', unlock: 'unblock',
                  registration: 'register', sign_up: 'cmon_let_me_in'
                 }
  resources :products, only: [:index, :show] do
    collection do
      get 'category/:category/' => 'products#category', as: 'category'
      get 'search' => 'products#search', as: 'search'
    end
  end

  post "basket/set_product" => 'basket#set_product', as: 'set_product'
  delete 'reset_basket' => 'basket#reset_basket'
  delete 'delete_basket_product/:id(.:format)', as: "delete_basket_product",
         to: 'basket#delete_basket_product'

  resources :orders, only: [:show, :new, :create]
  post "orders/:id(.:format)" => 'orders#show'
  resources :contact, only: [:index, :create]

  ######################### ADMIN ZONE ###############
  namespace :admin do
    get 'home' => 'home#index'
    post 'check_to_direct_link' => 'home#check_to_direct_link', as: 'check_to_direct_link'

    resources :users, except: [:show, :new, :create] do
      collection do
        get 'search' => 'users#search', as: 'search'
        get 'sort/:by' => 'users#sort', as: 'sort'
      end
    end

    #un producto puede contener imagenes de ProductPicture. Ademas se puede
    #buscar un producto desde el controlador producto en admin/product/search
    resources :products, except: [:show] do
      resources :product_pictures, only: [:create, :destroy]
      collection do
        get 'search' => 'products#search', as: 'search'
        get 'sort/:by' => 'products#sort', as: 'sort'
        get 'category/:category/' => 'products#category', as: 'category'
      end
    end

    resources :categories, except: [:show, :new, :edit]
    resources :post_categories, except: [:show, :new, :edit]

    resources :orders, only: [:index, :destroy, :update] do
      collection do
        get 'search' => 'orders#search', as: 'search'
        get 'sort/:by' => 'orders#sort', as: 'sort'
      end
    end

    resources :delivery_prices, except: [:show]

    resources :posts do
      collection do
        get 'search' => 'posts#search', as: 'search'
        get 'sort/:by' => 'posts#sort', as: 'sort'
        get 'category/:category/' => 'posts#category', as: 'category'
      end
    end

    resources :comments, except: [:show, :new, :create] do
      collection do
        get 'search' => 'comments#search', as: 'search'
      end
    end
  end
end

app/views/layouts/admin/_admin_navbar.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <br/><br/>
      </div>
      <div class="pull-left info">
        <p><%=current_user.name%></p>
        <p><small>(<%=t('admin_zone.global.admin_user')%>)</small></p>
      </div>
    </div>

    <ul class="sidebar-menu">
      <li class="header"><%=t('admin_zone.navbar.quick_access').upcase%></li>
      <li class="<%=set_active_admin_home_index%>"><a href="<%= admin_home_path %>"><i class="fa fa-circle-o text-red"></i> <span><%=t('admin_zone.navbar.home')%></span></a></li>
      <li><a href="<%=root_path%>"><i class="fa fa-circle-o text-yellow"></i> <span><%=t('admin_zone.navbar.return_store')%></span></a></li>
      <!--<li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>-->

      <li class="header"><%=t('admin_zone.navbar.main_nav_title').upcase%></li>
      <li class="<%=set_active_admin_users%> treeview">
        <a href="#">
          <i class="fa fa-users"></i> <span><%=t('admin_zone.navbar.users.name')%></span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li class="<%=set_active_admin_users_index%>"><a href="<%=admin_users_path%>"><i class="fa fa-circle-o"></i> <%=t('admin_zone.navbar.users.list')%></a></li>
          <!--<li class="<%=set_active_admin_users_new%>"><a href="#"><i class="fa fa-circle-o"></i> <%=t('admin_zone.navbar.users.create_user')%></a></li>-->
        </ul>
      </li>
      <li class="<%=set_active_admin_products%> treeview">
        <a href="#">
          <i class="fa fa-briefcase"></i>
          <span><%=t('admin_zone.navbar.products.name')%></span>
          <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li class="<%=set_active_admin_products_index%>"><a href="<%= admin_products_path %>"><i class="fa fa-circle-o"></i> <%=t('admin_zone.navbar.products.list_products')%></a></li>
          <li class="<%=set_active_admin_products_new%>"><a href="<%=new_admin_product_path%>"><i class="fa fa-circle-o"></i><%=t('admin_zone.navbar.products.create_product')%> </a></li>
        </ul>
      </li>
      <li class="<%=set_active_admin_categories%> treeview">
        <a href="#">
          <i class="fa fa-tags"></i>
          <span><%=t('admin_zone.navbar.categories.name')%></span>
          <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li class="<%=set_active_admin_categories_index%>"><a href="<%= admin_categories_path %>"><i class="fa fa-circle-o"></i> <%=t('admin_zone.navbar.categories.list')%></a></li>
        </ul>
      </li>
      <li class="<%=set_active_admin_delivery_prices%> treeview">
        <a href="#">
          <i class="fa fa-send"></i> <span> <%=t('admin_zone.navbar.delivery_prices.name')%></span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li class="<%=set_active_admin_delivery_prices_index%>"><a href="<%=admin_delivery_prices_path%>"><i class="fa fa-circle-o"></i> <%=t('admin_zone.navbar.delivery_prices.list')%></a></li>
          <li class="<%=set_active_admin_delivery_prices_new%>"><a href="<%=new_admin_delivery_price_path%>"><i class="fa fa-circle-o"></i> <%=t('common.new')%></a></li>
        </ul>
      </li>
      <li class="<%=set_active_admin_orders%> treeview">
        <a href="#">
          <i class="fa fa-shopping-cart "></i> <span><%=t('admin_zone.navbar.orders.name')%></span>
          <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li class="<%=set_active_admin_orders_index%>"><a href="<%=admin_orders_path%>"><i class="fa fa-circle-o"></i> <%=t('admin_zone.navbar.orders.list')%></a></li>
        </ul>
      </li>
      <li class="header"><%=t('admin_zone.navbar.main_nav_blog_title').upcase%></li>
      <li class="<%=set_active_admin_posts%> treeview">
        <a href="#">
          <i class="fa fa-cutlery "></i> <span> <%=t('admin_zone.posts.name')%></span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li class="<%=set_active_admin_posts_index%>"><a href="<%=admin_posts_path%>"><i class="fa fa-circle-o"></i> <%=t('admin_zone.posts.list')%></a></li>
          <li class="<%=set_active_admin_posts_new%>"><a href="<%=new_admin_post_path%>"><i class="fa fa-circle-o"></i> <%=t('common.new')%></a></li>
        </ul>
      </li>
      <li class="<%=set_active_admin_comments%> treeview">
        <a href="#">
          <i class="fa fa-comments"></i> <span> <%=t('admin_zone.comment.name')%></span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li class="<%=set_active_admin_comments_index%>"><a href="<%=admin_comments_path%>"><i class="fa fa-circle-o"></i> <%=t('admin_zone.comment.list')%></a></li>
        </ul>
      </li>
      <li class="<%=set_active_admin_post_categories%> treeview">
        <a href="#">
          <i class="fa fa-tags"></i>
          <span><%=t('admin_zone.navbar.categories.name')%></span>
          <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li class="<%=set_active_admin_post_categories_index%>"><a href="<%= admin_post_categories_path %>"><i class="fa fa-circle-o"></i> <%=t('admin_zone.navbar.categories.list')%></a></li>
        </ul>
      </li>

    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/admin/_customer_navbar.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <br/><br/>
      </div>
      <div class="pull-left info">
        <p><%=current_user.name%></p>
        <p><small>(<%=t('admin_zone.global.customer_user')%>)</small></p>
      </div>
    </div>

    <ul class="sidebar-menu">
      <li class="header"><%=t('admin_zone.navbar.quick_access').upcase%></li>
      <li class="<%=set_active_admin_home_index%>"><a href="<%= admin_home_path %>"><i class="fa fa-circle-o text-red"></i> <span><%=t('admin_zone.navbar.home')%></span></a></li>
      <li><a href="<%=root_path%>"><i class="fa fa-circle-o text-yellow"></i> <span><%=t('admin_zone.navbar.return_store')%></span></a></li>
      <!--<li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>-->

      <li class="header"><%=t('admin_zone.navbar.main_nav_title').upcase%></li>
      <li class="<%=set_active_customer_user%> treeview">
        <a href="#">
          <i class="fa fa-user"></i> <span><%=t('admin_zone.navbar.users.name2')%></span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li class="<%=set_active_customer_user_update%>"><a href="<%= edit_user_registration_path %>"><i class="fa fa-circle-o"></i> <%=t('admin_zone.navbar.users.edit_user')%></a></li>
        </ul>
      </li>

      <li class="<%=set_active_admin_orders%> treeview">
        <a href="#">
          <i class="fa fa-shopping-cart "></i> <span><%=t('admin_zone.navbar.orders.name')%></span>
          <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li class="<%=set_active_admin_orders_index%>"><a href="<%=admin_orders_path%>"><i class="fa fa-circle-o"></i> <%=t('admin_zone.navbar.orders.list')%></a></li>
        </ul>
      </li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/admin/_widget_direct_link.html.erb
<div class="jumbotron">
<%= form_for(:search, url:   admin_check_to_direct_link_path , method: 'post', remote: true,html: {class: 'form'}) do |f| %>
    <div class="box-body">
        <div class="form-group">
          <%= f.text_field :url, placeholder: t('admin_zone.global.convert_url'), class: 'form-control input-lg' %>
          <%= f.submit t('common.accept'), class: 'btn btn-info' %><br/><br/>
          <div id="direct_link"></div>
        </div>
    </div>
<% end %>
</div>

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<html lang="<%=I18n.locale%>">
<head>
  <title><%= @web_title %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="/assets/favicon.ico">
  <meta charset="utf-8">
  <meta http-equiv="Content-Language" content="<%=I18n.locale%>"/>
  <meta name="distribution" content="iu"/>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="<%= @description %>">
  <meta http-equiv="content-type" content="text/html;charset=UTF-8">
</head>
<body class="hold-transition skin-blue sidebar-mini" style="font-size: 14px" data-no-turbolink>
<div class="wrapper">
  <header class="main-header">
    <!-- Logo -->
    <a href="<%= root_path %>" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><img src="/assets/logo.png" class="text-left" alt="logo" height="" width="200"> <b></b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <span class="clock_admin"><%= l Time.new, format: :long2 %></span>
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown pull-right">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%="<i class=\"fa fa-warning text-yellow \" style=\"font-size:20px;\"></i> ".html_safe if current_user.is_admin?%> <i class="fa fa-user " style="font-size:20px;"> <%=current_user.name%> </i>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="<%=root_path%>"><i class="fa fa-circle-o text-yellow"></i> <span><%=t('admin_zone.navbar.return_store')%></span></a></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "<i class='fa fa-sign-out'></i> #{t('devise.links.sign_out')}".html_safe, destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
          <!-- Control Sidebar Toggle Button -->
<!--          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>-->
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <% if current_user.is_admin? %>
      <%= render 'layouts/admin/admin_navbar' %>
  <% elsif current_user.is_customer? %>
      <%= render 'layouts/admin/customer_navbar' %>
  <% end %>
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-xs-12 thumb">
        <% if notice.present? %>
            <div class="alert alert-success alert-dismissable">
              <i class="fa fa-thumbs-o-up"></i>
              <strong><%= t('common.info') %></strong>
              <%= notice.html_safe %>
              <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
            </div>
        <% end %>
        <% if alert.present? %>
            <div class="alert alert-danger alert-dismissable">
              <i class="fa fa-warning"></i>
              <strong><%= t('common.danger') %></strong>
              <%= alert.html_safe %>
              <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
            </div>
        <% end %>
      </div>
    </div>
    <%= yield %>
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Ver.</b> 1.2
    </div>
    <strong>Copyright &copy; <%= Time.now.year %> <a href="http://tejeycome.es">TejeyCome</a>.</strong> Todos los
    derechos reservados.
  </footer>
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript::;">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript::;">
              <i class="menu-icon fa fa-user bg-yellow"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                <p>New phone +1(800)555-1234</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript::;">
              <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                <p>nora@example.com</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript::;">
              <i class="menu-icon fa fa-file-code-o bg-green"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                <p>Execution time 5 seconds</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript::;">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="label label-danger pull-right">70%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript::;">
              <h4 class="control-sidebar-subheading">
                Update Resume
                <span class="label label-success pull-right">95%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-success" style="width: 95%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript::;">
              <h4 class="control-sidebar-subheading">
                Laravel Integration
                <span class="label label-warning pull-right">50%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript::;">
              <h4 class="control-sidebar-subheading">
                Back End Framework
                <span class="label label-primary pull-right">68%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Allow mail redirect
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Other sets of options are available
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Expose author name in posts
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Allow the user to show his name in blog posts
            </p>
          </div>
          <!-- /.form-group -->

          <h3 class="control-sidebar-heading">Chat Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Show me as online
              <input type="checkbox" class="pull-right" checked>
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Turn off notifications
              <input type="checkbox" class="pull-right">
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Delete chat history
              <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
            </label>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>

  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

</body>
</html>