config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root "home#index"
  get 'legal' => 'home#legal', as: 'legal'
  resources :how_do, only: [:index]
  resources :blog, only: [:index, :show] do
    resources :comments, only: [:create] do
    end
    collection do
      get 'category/:category/' => 'blog#category', as: 'category'
      get 'do_pdf/:post/' => 'blog#do_pdf', as: 'do_pdf'
    end
  end

  devise_for :users,
             controllers: {registrations: 'users/registrations'},
             path: "auth",
             path_names:
                 {sign_in: 'login', sign_out: 'logout', password: 'secret',
                  confirmation: 'verification', unlock: 'unblock',
                  registration: 'register', sign_up: 'cmon_let_me_in'
                 }
  resources :products, only: [:index, :show] do
    collection do
      get 'category/:category/' => 'products#category', as: 'category'
      get 'search' => 'products#search', as: 'search'
    end
  end

  post "basket/set_product" => 'basket#set_product', as: 'set_product'
  delete 'reset_basket' => 'basket#reset_basket'
  delete 'delete_basket_product/:id(.:format)', as: "delete_basket_product",
         to: 'basket#delete_basket_product'

  resources :orders, only: [:show, :new, :create]
  post "orders/:id(.:format)" => 'orders#show'
  resources :contact, only: [:index, :create]

  ######################### ADMIN ZONE ###############
  namespace :admin do
    get 'home' => 'home#index'
    post 'check_to_direct_link' => 'home#check_to_direct_link', as: 'check_to_direct_link'

    resources :users, except: [:show, :new, :create] do
      collection do
        get 'search' => 'users#search', as: 'search'
        get 'sort/:by' => 'users#sort', as: 'sort'
      end
    end

    #un producto puede contener imagenes de ProductPicture. Ademas se puede
    #buscar un producto desde el controlador producto en admin/product/search
    resources :products, except: [:show] do
      resources :product_pictures, only: [:create, :destroy]
      collection do
        get 'search' => 'products#search', as: 'search'
        get 'sort/:by' => 'products#sort', as: 'sort'
        get 'category/:category/' => 'products#category', as: 'category'
      end
    end

    resources :categories, except: [:show, :new, :edit]
    resources :post_categories, except: [:show, :new, :edit]

    resources :orders, only: [:index, :destroy, :update] do
      collection do
        get 'search' => 'orders#search', as: 'search'
        get 'sort/:by' => 'orders#sort', as: 'sort'
      end
    end

    resources :delivery_prices, except: [:show]

    resources :posts do
      collection do
        get 'search' => 'posts#search', as: 'search'
        get 'sort/:by' => 'posts#sort', as: 'sort'
        get 'category/:category/' => 'posts#category', as: 'category'
      end
    end

    resources :comments, except: [:show, :new, :create] do
      collection do
        get 'search' => 'comments#search', as: 'search'
      end
    end
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  before_filter :authenticate_user! # es necesario estar autenticado para continuar
  authorize_resource class: false
  layout 'admin/admin'
  include ConvertToDirectLink

  def index
    if current_user.is_customer?
      @last_order=@orders = Order.from_current_customer(current_user).last
      render :index_customer
    elsif current_user.is_admin?
      @area_chart_orders_this_month=Order.this_month.group_by_day(:created_at, format: "%d/%B/%Y").maximum(:price)
      @pie_products_by_main_categories=calc_pie_products_by_main_categories
      @column_chart_by_users=User.this_year.group_by_month(:created_at,format: "%d/%b/%Y").count
      render :index
    end
  end

  private
  def calc_pie_products_by_main_categories
    result=Array.new
    num_products=0
    Category.mains.each do |category|
      num_products+=category.products.count
      category.subcategories.each do |subcategory|
        num_products+=subcategory.products.count
      end
      result << [category.name,num_products]
      num_products=0
    end
    result
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @carousel_products=Product.random4
    @carousel_posts=Post.random4
    @last_4_products=Product.last(4).reverse
    @last_4_posts=Post.last(4).reverse
    @web_title='TejeyCome.es - Home'
  end
  def legal
    @web_title='TejeyCome.es - Aviso Legal'
  end

end

app/views/home/_carouser_home.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <ol class="hidden-xs carousel-indicators">
    <%@carousel_products.each_with_index do |product, index|%>
        <li data-target="#carousel-example-generic" data-slide-to="<%=index%>" class="<%='active' if index==0%>"></li>
    <%end%>
    <%@carousel_posts.each_with_index do |post, index|%>
        <li data-target="#carousel-example-generic" data-slide-to="<%=index+@carousel_products.count%>" class="<%='active' if index==0%>"></li>
    <%end%>
  </ol>
  <div class="carousel-inner">
    <%@carousel_products.each_with_index do |product,index|%>
        <div class="item <%='active' if index==0%>">
          <%= image_tag product.media,size: "500", class: "img-responsive center-block" %>
          <div class="carousel-caption">
            <%=link_to product.name+ " (#{product.price}€)", product_path(product)%>
          </div>
        </div>
    <%end%>
    <%@carousel_posts.each_with_index do |post,index|%>
        <div class="item">
          <%= image_tag post.media,size:"500", class: "img-responsive center-block" %>
          <div class="carousel-caption">
            <%=link_to post.title, blog_path(post)%>
          </div>
        </div>
    <%end%>
  </div>
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="fa fa-angle-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="fa fa-angle-right"></span>
  </a>
</div>

app/views/home/index.html.erb
<div class="">
  <div class="row home_header">
    <div class="col-xs-12 col-md-6">
      <div class="center-block">
        <%= image_tag 'logo.png', class: 'img-responsive center-block' %>
        <h3 class="text-center text-green"><%=t('home.older')%></h3>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div class="center-block">
        <h1 class="handwriting center-block">" <%=t('home.description').html_safe%> " </h1>
      </div>
    </div>
  </div>
  <div class="row">
    <%= render 'home/carouser_home' %>
  </div>
  <br/>

  <div class="row">
    <div class="">
      <div class="col-xs-12 box_efect2">
        <div class="thumbnail boxeffect  home_padding">
          <h2><%= icon('slack') %> <%= t('home.activity5-title') %></h2>
          <p><%= t('home.activity5-description') %></p>
          <div class="row">
            <% @last_4_products.each do |product| %>
                <div class="col-xs-12 col-md-3">
                  <%= image_tag product.media, class: 'img-responsive' %>
                  <%=link_to product.name+ " (#{product.price}€)", product_path(product)%>
                </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-xs-12 box_efect2">
        <div class="thumbnail boxeffect  home_padding">
          <div class="row">
            <h2 class="pull-right"><%= t('home.activity6-title') %> <%= icon('cutlery') %> </h2>
          </div>
          <p><%= t('home.activity6-description') %></p>
          <div class="row">
            <% @last_4_posts.each do |post| %>
                <div class="col-xs-12 col-md-3">
                  <%= image_tag post.media, class: 'img-responsive' %>
                  <%=link_to post.title, blog_path(post)%>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /container -->